spring.application.name=product-erp_2408039
# Give your application a name

# Enable the H2 Console (very useful for debugging)
spring.h2.console.enabled=true
# This is the URL path to access the database UI
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:productdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate/JPA settings
# 'update' means Hibernate will automatically create/update your table based on your @Entity
spring.jpa.hibernate.ddl-auto=update
# This prints the SQL queries in your terminal so you can see what's happening
spring.jpa.show-sql=true